version: '2'

services:
  gotools_build:
    image: golang
    volumes:
      - $PWD:/go/src/github.com/istreeter/gotools
      - $HOME/go:/go
    command: go test github.com/istreeter/gotools/stasher
